import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';
import { render, screen, cleanup } from '@testing-library/react';
import { PluginHostProvider } from '../../plugin-host/plugin-host-context';
import { FrontendPluginHost } from '../../plugin-host/plugin-host';
import { setSocketInstance } from '../../services/socket-service';
import { AppShell, AppShellProps } from '../AppShell';

beforeEach(() => {
  setSocketInstance({
    on: vi.fn(),
    off: vi.fn(),
    emit: vi.fn(),
    disconnect: vi.fn(),
  } as any);
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

// StudentViewProps defaults (mirrors src/features/student/__tests__/StudentView.test.tsx).
const studentDefaults: any = {
  students: [{ id: 's1', name: 'Alice' }],
  activeStudentId: 's1',
  studentViewStatus: 'dashboard',
  studentDashboardData: {
    progress: [],
    assignments: [{ id: 'a1', title: 'HW', class_name: 'C', content: 'x', submission_status: null }],
    schedules: [],
    rollcalls: [],
    classes: [],
  },
  readNotifications: new Set<string>(),
  setReadNotifications: vi.fn(),
  addToast: vi.fn(),
  lang: 'en',
  setSelectedLesson: vi.fn(),
  setStudentViewStatus: vi.fn(),
  setSelectedAssignment: vi.fn(),
  setQuizStudentAnswers: vi.fn(),
  setSubAssignmentTab: vi.fn(),
  lessons: [{ id: 'l1', title: 'Lesson 1' }],
  selectedLesson: 'l1',
  studentFullscreenPanel: 'none',
  setStudentFullscreenPanel: vi.fn(),
  timelineSegments: [],
  activeSegmentId: null,
  setActiveSegmentId: vi.fn(),
  localProgressPercent: 0,
  setLocalProgressPercent: vi.fn(),
  updateStudentProgress: vi.fn(),
  isStudentLessonContentCollapsed: false,
  setIsStudentLessonContentCollapsed: vi.fn(),
  studentLessonTab: 'whiteboard',
  setStudentLessonTab: vi.fn(),
  elements: [],
  activeRole: 'student',
  fetchElements: vi.fn(),
  currentVfsParent: null,
  setCurrentVfsParent: vi.fn(),
  vfsNodes: [],
  studentSelectedCourseware: null,
  setStudentSelectedCourseware: vi.fn(),
  selectedAssignment: null,
  quizStudentAnswers: {},
  submitQuizAssignment: vi.fn(),
  subAssignmentTab: 'quiz',
};

// TeacherViewProps defaults (mirrors src/features/teacher/__tests__/TeacherView.test.tsx).
const teacherDefaults: any = {
  mainNavCollapsed: false,
  setMainNavCollapsed: vi.fn(),
  teacherTab: 'dashboard',
  setTeacherTab: vi.fn(),
  lang: 'en',
  session: null,
  todaySchedules: [],
  t: (k: string) => k,
  lessons: [],
  classes: [],
  students: [],
  approvals: [],
  processes: [],
  isApprovalsCollapsed: false,
  setIsApprovalsCollapsed: vi.fn(),
  isProcessesCollapsed: false,
  setIsProcessesCollapsed: vi.fn(),
  scoreOverrides: {},
  setScoreOverrides: vi.fn(),
  handleApprove: vi.fn(),
  handleReject: vi.fn(),
  showLogs: false,
  setShowLogs: vi.fn(),
  processLogsContent: '',
  showProcessLogs: null,
  fetchProcessLogs: vi.fn(),
  setShowProcessLogs: vi.fn(),
  addToast: vi.fn(),
  handleQuickScheduleClass: vi.fn(),
  handleQuickGenerateAssignment: vi.fn(),
  handleQuickCreateLesson: vi.fn(),
  selectedLesson: null,
  activeRole: 'teacher',
  setActiveRole: vi.fn(),
  editorSaveStatus: 'none',
  setEditorSaveStatus: vi.fn(),
  editorLastSavedTime: null,
  setEditorLastSavedTime: vi.fn(),
  setIsLessonPreviewVisible: vi.fn(),
  setPreviewLessonTab: vi.fn(),
  setPreviewSelectedCourseware: vi.fn(),
  handlePaletteActivate: vi.fn(),
  timelineSegments: [],
  activeSegmentId: null,
  setActiveSegmentId: vi.fn(),
  draggedSegmentIdx: null,
  setDraggedSegmentIdx: vi.fn(),
  saveTimeline: vi.fn(),
  editorPanelsExpanded: false,
  setEditorPanelsExpanded: vi.fn(),
  fetchElements: vi.fn(),
  whiteboardRef: { current: null },
  elements: [],
  paletteEdit: null,
  handlePaletteConfirm: vi.fn(),
  setPaletteEdit: vi.fn(),
  setSelectedLesson: vi.fn(),
  plugins: [],
  liveClassSelectedClassId: null,
  setLiveClassSelectedClassId: vi.fn(),
  liveClassIsActive: false,
  setLiveClassIsActive: vi.fn(),
  liveClassTimeRemaining: 0,
  setLiveClassTimeRemaining: vi.fn(),
  liveClassFeed: [],
  setLiveClassFeed: vi.fn(),
  liveClassAcknowledgedMap: new Map(),
  setLiveClassAcknowledgedMap: vi.fn(),
  onlineStudentIds: [],
  activeStudentLessons: {},
  liveClassStudentProgress: [],
  onPingStudent: vi.fn(),
  onOpenCoursewareHub: vi.fn(),
  storeTab: 'store',
  setStoreTab: vi.fn(),
  pluginCode: '',
  setPluginCode: vi.fn(),
  installingPlugin: false,
  onInstall: vi.fn(),
  onZipUpload: vi.fn(),
  onToggle: vi.fn(),
  onDelete: vi.fn(),
  lessonsSearchQuery: '',
  setLessonsSearchQuery: vi.fn(),
  lessonsSortOrder: 'recent',
  setLessonsSortOrder: vi.fn(),
  filteredLessons: [],
  onOpenImportLessons: vi.fn(),
  onOpenCourseWizard: vi.fn(),
  onViewCourse: vi.fn(),
  onDeleteCourse: vi.fn(),
  onCopyCourse: vi.fn(),
  filterEnrollment: false,
  setFilterEnrollment: vi.fn(),
  filterHasContent: false,
  setFilterHasContent: vi.fn(),
  filterThisMonth: false,
  setFilterThisMonth: vi.fn(),
  copyingLessonId: null,
  onSchedulesUpdated: vi.fn(),
  onLogout: vi.fn(),
  aiProviders: [],
  testingProviderId: null,
  onAIProvidersChanged: vi.fn(),
  onTriggerTour: vi.fn(),
  siteInfo: {},
  onSiteInfoChanged: vi.fn(),
  computerLabs: [],
  onRefresh: vi.fn(),
  registeredCommands: [],
  fetchRegisteredCommands: vi.fn(),
  batchMode: false,
  selectedClassIds: new Set<string>(),
  setSelectedClassIds: vi.fn(),
  setSelectedStudentIds: vi.fn(),
  setBatchMode: vi.fn(),
  expandedClassId: null,
  setExpandedClassId: vi.fn(),
  exportTooltipOpen: false,
  setExportTooltipOpen: vi.fn(),
  exportDropdownOpen: false,
  setExportDropdownOpen: vi.fn(),
  isExportingAllCombined: false,
  loadingExportClassId: null,
  classStudentsMap: {},
  setClassStudentsMap: vi.fn(),
  expandedStudentId: null,
  setExpandedStudentId: vi.fn(),
  selectedStudentIds: new Set<string>(),
  rosterViewMode: 'grid',
  setRosterViewMode: vi.fn(),
  rosterSearchQuery: '',
  setRosterSearchQuery: vi.fn(),
  rosterTagFilter: 'all',
  setRosterTagFilter: vi.fn(),
  toggleSelectAllStudents: vi.fn(),
  handleBatchDeleteStudents: vi.fn(),
  handleBatchResetPassword: vi.fn(),
  handleBatchTransferStudents: vi.fn(),
  handleBatchSetLockedLesson: vi.fn(),
  toggleStudentSelection: vi.fn(),
  get30DayAverageWarning: vi.fn(),
  studentProgressMap: {},
  studentActiveTabs: {},
  setStudentActiveTabs: vi.fn(),
  setStudents: vi.fn(),
  fetchClassStudents: vi.fn(),
  fetchStudents: vi.fn(),
  parseCSV: vi.fn(),
  setImportError: vi.fn(),
  setImportSuccess: vi.fn(),
  setShowImportModal: vi.fn(),
  fetchClasses: vi.fn(),
  classSubmissionFilters: {},
  setClassSubmissionFilters: vi.fn(),
  classActiveTabs: {},
  setClassActiveTabs: vi.fn(),
  classProgressMap: {},
  classSchedulesMap: {},
  classDashboardMap: {},
  assignmentSortOrder: 'dueDate',
  setAssignmentSortOrder: vi.fn(),
  isGeneratingPDFReport: {},
  handleGeneratePDFReport: vi.fn(),
  setExportClassId: vi.fn(),
  setExportClassName: vi.fn(),
  setQuizzesWeight: vi.fn(),
  setAssignmentsWeight: vi.fn(),
  setCustomCategoryOverrides: vi.fn(),
  setIsExportWeightModalOpen: vi.fn(),
  isGeneratingAssignment: null,
  setQuizGeneratorClassId: vi.fn(),
  setQuizGenMode: vi.fn(),
  setQuizGenSelectedLessonId: vi.fn(),
  setQuizGenTopic: vi.fn(),
  setSuggestedObjectives: vi.fn(),
  setSuggestedQuestions: vi.fn(),
  setIsQuizGeneratorOpen: vi.fn(),
  setActiveStudentId: vi.fn(),
  setSelectedAssignment: vi.fn(),
  setStudentViewStatus: vi.fn(),
  isGrading: {},
  setIsGrading: vi.fn(),
  fetchClassDashboard: vi.fn(),
  newScheduleDate: '',
  setNewScheduleDate: vi.fn(),
  newScheduleLessonId: '',
  setNewScheduleLessonId: vi.fn(),
  expandedScheduleId: null,
  setExpandedScheduleId: vi.fn(),
  fetchScheduleAttendance: vi.fn(),
  scheduleAttendanceMap: {},
  toggleSelectAllClasses: vi.fn(),
  handleBatchDeleteClasses: vi.fn(),
  handleBatchExportClasses: vi.fn(),
  handleBatchSetPasscode: vi.fn(),
  handleBatchScheduleClasses: vi.fn(),
  handleExportAllClassesCombined: vi.fn(),
  triggerExportForClass: vi.fn(),
  fetchClassProgress: vi.fn(),
  fetchClassSchedules: vi.fn(),
  fetchStudentProgress: vi.fn(),
  toggleClassSelection: vi.fn(),
  socketRef: { current: null },
  setShowCoursewareHub: vi.fn(),
  fetchTodaySchedules: vi.fn(),
};

function makeProps(overrides: Record<string, unknown> = {}): AppShellProps {
  return { ...teacherDefaults, ...studentDefaults, ...overrides } as unknown as AppShellProps;
}

const renderAppShell = (overrides: Record<string, unknown> = {}) =>
  render(
    <PluginHostProvider host={new FrontendPluginHost()}>
      <AppShell {...makeProps(overrides)} />
    </PluginHostProvider>,
  );

describe('AppShell', () => {
  it('renders StudentView (and the "No Student Selected" panel) when activeRole is "student"', async () => {
    renderAppShell({ activeRole: 'student', activeStudentId: null });
    expect(await screen.findByText('No Student Selected')).toBeTruthy();
    // The teacher-only branch must NOT be present.
    expect(screen.queryByText('Live Class')).toBeNull();
  });

  it('renders TeacherView (NavigationSidebar) when activeRole is "teacher"', async () => {
    renderAppShell({ activeRole: 'teacher' });
    // TeacherView carries the bg-gray-50 branch root and always renders the nav sidebar.
    expect(await screen.findByText('Live Class')).toBeTruthy();
    // The student-only branch must NOT be present.
    expect(screen.queryByText('No Student Selected')).toBeNull();
  });
});
