/**
 * EventForwarder — main-thread event forwarding layer for Worker-isolated plugins.
 *
 * When a Worker plugin calls `eventBus.subscribe('lesson.created', handler)`,
 * the ServiceHost routes the subscribe message to EventForwarder. EventForwarder
 * subscribes to the real EventBus with a forwarding handler that serializes the
 * event and posts it to the Worker via IWorkerTransport. The Worker-side
 * EventBusProxy dispatches the forwarded event to local handlers.
 *
 * ## Architecture
 *
 * ```
 * Worker: eventBus.subscribe('lesson.created', handler)
 *   -> transport.postMessage({ type: 'subscribe', subId, eventType })
 *   -> Main thread: ServiceHost.handleSubscribe
 *     -> EventForwarder.handleSubscribe
 *       -> eventBus.subscribe(eventType, forwardHandler)
 *       -> (on event publish) transport.postMessage({ type: 'event', subId, event })
 *         -> Worker: EventBusProxy.handleEvent(subId, event)
 *           -> dispatches to local handlers
 * ```
 *
 * ## Subscription Tracking
 *
 * Each Worker has its own EventForwarder instance (lazily created by ServiceHost).
 * Subscriptions are tracked in a nested Map structure:
 * - Outer key: transport.id (Worker ID)
 * - Inner key: subId (generated by Worker-side EventBusProxy)
 * - Value: { handler (forwarding function), unsubscribe (EventBus cleanup function) }
 *
 * The forwarding handler function reference is stored so handleUnsubscribe can pass
 * the SAME reference to eventBus.unsubscribe() -- EventBus uses Set-based subscriber
 * tracking which requires identical reference for deletion.
 *
 * @module
 */

import type { EventBus, EventSubscriber, PlatformEvent } from '../event-bus/index.js';
import type { IWorkerTransport, SubscribeMessage, UnsubscribeMessage } from './types.js';

// -- EventForwarder ---------------------------------------------------------------

/**
 * EventForwarder -- manages EventBus subscriptions on behalf of a Worker.
 *
 * For a given Worker (identified by transport.id), this class:
 * 1. Receives 'subscribe' messages -> subscribes to real EventBus with a forwarder
 * 2. Receives 'unsubscribe' messages -> removes the EventBus listener
 * 3. On Worker termination -> disposes all subscriptions (disposeAll)
 *
 * One EventForwarder instance per Worker. Created lazily on first subscribe.
 */
export class EventForwarder {
  /**
   * Per-Worker subscription tracking.
   *
   * ```
   * Map<transportId, Map<subId, { handler, unsubscribe }>>
   * ```
   *
   * - transportId: from IWorkerTransport.id, uniquely identifies the Worker
   * - subId: generated by Worker-side EventBusProxy, used for matching unsubscribe
   * - handler: the forwarding EventSubscriber function (must be stored for
   *   unsubscribe reference equality)
   * - unsubscribe: function that removes the handler from EventBus
   */
  private subscriptions = new Map<
    string,
    Map<string, { handler: EventSubscriber; unsubscribe: () => void }>
  >();

  /**
   * @param eventBus - The real EventBus instance to subscribe to
   * @param transport - The Worker transport to forward events through
   */
  constructor(
    private readonly eventBus: EventBus,
    private readonly transport: IWorkerTransport,
  ) {}

  // -- Public API -----------------------------------------------------------------

  /**
   * Handle a 'subscribe' message from the Worker.
   *
   * Creates a forwarding handler that posts serialized events to the Worker,
   * subscribes it to the real EventBus, and stores the references for cleanup.
   *
   * @param msg - The subscribe message with subId and eventType
   */
  handleSubscribe(msg: SubscribeMessage): void {
    const { subId, eventType } = msg;

    // Create the forwarding handler -- this function is passed to EventBus.subscribe()
    // and must be stored so we can pass the SAME reference to EventBus.unsubscribe().
    const forwardHandler: EventSubscriber = (event: PlatformEvent) => {
      try {
        this.transport.postMessage({
          type: 'event' as const,
          subId,
          event: {
            id: event.id,
            type: event.type,
            source: event.source,
            payload: event.payload,
            timestamp: event.timestamp,
            correlationId: event.correlationId,
          },
        });
      } catch (err) {
        // Worker may already be terminated -- log and continue
        console.error(
          `[EventForwarder] Failed to forward event "${eventType}" to Worker "${this.transport.id}":`,
          err,
        );
      }
    };

    // Subscribe to the real EventBus
    this.eventBus.subscribe(eventType, forwardHandler);

    // Create the unsubscribe function
    const unsubscribe = () => {
      this.eventBus.unsubscribe(eventType, forwardHandler);
    };

    // Track in per-Worker subscriptions map
    let workerSubs = this.subscriptions.get(this.transport.id);
    if (!workerSubs) {
      workerSubs = new Map();
      this.subscriptions.set(this.transport.id, workerSubs);
    }
    workerSubs.set(subId, { handler: forwardHandler, unsubscribe });
  }

  /**
   * Handle an 'unsubscribe' message from the Worker.
   *
   * Looks up the stored unsubscribe function for the given subId and calls it
   * to remove the forwarding handler from EventBus.
   *
   * @param msg - The unsubscribe message with subId
   */
  handleUnsubscribe(msg: UnsubscribeMessage): void {
    const workerSubs = this.subscriptions.get(this.transport.id);
    if (!workerSubs) return;

    const entry = workerSubs.get(msg.subId);
    if (!entry) return;

    // Call the stored unsubscribe function to remove from EventBus
    entry.unsubscribe();
    workerSubs.delete(msg.subId);
  }

  /**
   * Dispose all subscriptions for this Worker.
   *
   * Unsubscribes all forwarding handlers from EventBus and clears the tracking Map.
   * Called when the Worker terminates (via ServiceHost.disposeEventForwarder).
   *
   * Idempotent -- calling disposeAll() multiple times has no effect.
   */
  disposeAll(): void {
    const workerSubs = this.subscriptions.get(this.transport.id);
    if (!workerSubs) return;

    for (const [, entry] of workerSubs) {
      try {
        entry.unsubscribe();
      } catch (err) {
        console.error(
          `[EventForwarder] Error unsubscribing for Worker "${this.transport.id}":`,
          err,
        );
      }
    }

    workerSubs.clear();
    this.subscriptions.delete(this.transport.id);
  }
}
