/**
 * Worker-side transparent RPC Proxy for cross-boundary service calls.
 *
 * Creates JavaScript Proxy objects that intercept property access and method
 * calls, serialize them as 'invoke' messages, and send them via IWorkerTransport
 * to the main thread ServiceHost. The calling code (Worker-side plugin) is not
 * aware it is calling across a thread boundary.
 *
 * ## Architecture
 *
 * ```
 * Plugin code -> services.commandBus.execute(cmd)
 *                     |
 *         createMethodProxy (Proxy get trap)
 *                     |
 *         pendingCalls.set(invokeId, { resolve, reject })
 *                     |
 *         transport.postMessage({ type: 'invoke', invokeId, token, method, args })
 *                     |
 *         (main thread processes, returns result/error)
 *                     |
 *         onMessage handler matches invokeId -> resolve/reject pending
 * ```
 *
 * ## Timeouts
 *
 * Each method call has a configurable timeout (default 30s). If no response
 * arrives within the timeout, the promise rejects with WorkerTimeoutError.
 * The pending call is deleted from the Map and the timeout is cleared on
 * response arrival.
 *
 * @module
 */

import type { IWorkerTransport, PendingCall } from './types.js';
import { WorkerTimeoutError, WorkerTransportError } from './errors.js';

// ── createMethodProxy ──────────────────────────────────────────────────────

/**
 * Create a JavaScript Proxy that transparently forwards method calls to the
 * main thread via IWorkerTransport.
 *
 * The returned Proxy's `get` trap returns an async function that:
 * 1. Generates a unique invokeId via `crypto.randomUUID()`
 * 2. Stores `{ resolve, reject }` in the shared pendingCalls Map
 * 3. Posts an `'invoke'` message via transport
 * 4. Returns a Promise that resolves/rejects when the response arrives
 *
 * @param transport - Worker transport for cross-thread messaging
 * @param token - Service token string (e.g. `'@openlearn/core:ICommandBusService'`)
 * @param pendingCalls - Shared Map for matching invoke responses by invokeId
 * @param timeoutMs - Per-call timeout in ms (0 = no timeout, default 30000)
 * @returns A Proxy-wrapped object where property access returns callable functions
 */
export function createMethodProxy(
  transport: IWorkerTransport,
  token: string,
  pendingCalls: Map<string, PendingCall>,
  timeoutMs: number = 30000,
): Record<string, Function> {
  return new Proxy({} as Record<string, Function>, {
    get(
      _target: Record<string, Function>,
      method: string | symbol,
    ): Function {
      // Return an async invoke function for any property access
      return (...args: unknown[]) => {
        const invokeId = crypto.randomUUID();
        let timeoutId: ReturnType<typeof setTimeout> | undefined;

        const promise = new Promise<unknown>((resolve, reject) => {
          // Wrap resolve/reject to clear the timeout on response arrival
          const wrappedResolve = (value: unknown) => {
            if (timeoutId) clearTimeout(timeoutId);
            resolve(value);
          };
          const wrappedReject = (err: Error) => {
            if (timeoutId) clearTimeout(timeoutId);
            reject(err);
          };

          // Register the pending call
          pendingCalls.set(invokeId, {
            resolve: wrappedResolve,
            reject: wrappedReject,
          });

          // Send the invoke message
          transport.postMessage({
            type: 'invoke',
            invokeId,
            token,
            method: String(method),
            args,
          });

          // Set timeout if enabled
          if (timeoutMs > 0 && timeoutMs < Infinity) {
            timeoutId = setTimeout(() => {
              pendingCalls.delete(invokeId);
              wrappedReject(new WorkerTimeoutError(timeoutMs));
            }, timeoutMs);
          }
        });

        return promise;
      };
    },
  });
}

// ── EventBusProxy ─────────────────────────────────────────────────────────

/**
 * EventBusProxy -- Worker-side event subscription proxy.
 *
 * Intercepts eventBus.subscribe() and eventBus.unsubscribe() calls,
 * sends subscribe/unsubscribe messages to main thread, and dispatches
 * forwarded events to local handlers.
 *
 * Structured clone cannot transfer functions -- the subId proxy pattern
 * keeps handler functions in the Worker and sends only subId + eventType
 * across the boundary. (See RESEARCH.md Common Pitfall 1)
 *
 * @example
 * ```ts
 * const proxy = new EventBusProxy(transport);
 * proxy.subscribe('lesson.created', (event) => console.log(event));
 * // sends { type: 'subscribe', subId: '...', eventType: 'lesson.created' }
 * ```
 */
export class EventBusProxy {
  /**
   * Map<subId, handlers[]> -- each subId can have multiple handlers.
   * The subId is generated by subscribe() and sent to main thread for
   * matching forwarded events.
   */
  private subscriptions = new Map<string, Array<(event: any) => void>>();

  constructor(private transport: IWorkerTransport) {}

  /**
   * Subscribe to an event type. Generates subId, sends subscribe message
   * to main thread, tracks the handler for dispatch when forwarded events
   * arrive via handleEvent.
   *
   * @param eventType - The event type to subscribe to (e.g. 'lesson.created')
   * @param handler - Callback invoked when a forwarded event of this type arrives
   * @returns The subId string, useful for manual unsubscription
   */
  subscribe(eventType: string, handler: (event: any) => void): string {
    const subId = crypto.randomUUID();
    const handlers = this.subscriptions.get(subId) ?? [];
    handlers.push(handler);
    this.subscriptions.set(subId, handlers);

    this.transport.postMessage({
      type: 'subscribe' as const,
      subId,
      eventType,
    });
    return subId;
  }

  /**
   * Unsubscribe a handler. If it was the last handler for a subId,
   * sends unsubscribe message to main thread to clean up the
   * EventForwarder subscription on the EventBus.
   *
   * @param eventType - The event type to unsubscribe from
   * @param handler - The handler function previously passed to subscribe()
   */
  unsubscribe(eventType: string, handler: (event: any) => void): void {
    for (const [subId, handlers] of this.subscriptions) {
      const idx = handlers.indexOf(handler);
      if (idx !== -1) {
        handlers.splice(idx, 1);
        if (handlers.length === 0) {
          this.subscriptions.delete(subId);
          this.transport.postMessage({
            type: 'unsubscribe' as const,
            subId,
          });
        }
        break;
      }
    }
  }

  /**
   * Handle an incoming forwarded event from main thread.
   * Called by the onMessage handler in the Worker bootstrap code
   * when an 'event' type message arrives.
   *
   * @param subId - The subscription ID matching the original subscribe() call
   * @param event - The forwarded PlatformEvent
   */
  handleEvent(subId: string, event: any): void {
    const handlers = this.subscriptions.get(subId);
    if (!handlers) return;
    for (const handler of handlers) {
      try {
        handler(event);
      } catch (err) {
        console.error('[EventBusProxy] Handler error:', err);
      }
    }
  }

  /**
   * Clean up all subscriptions (called when Worker is shutting down).
   * Sends unsubscribe for all active subIds to clean up EventForwarder
   * subscriptions on the main thread.
   */
  disposeAll(): void {
    for (const [subId] of this.subscriptions) {
      this.transport.postMessage({
        type: 'unsubscribe' as const,
        subId,
      });
    }
    this.subscriptions.clear();
  }
}

// ── createServicesProxy ────────────────────────────────────────────────────

/**
 * Result of {@link createServicesProxy}.
 */
export interface ServicesProxyResult {
  /**
   * Frozen services object with Proxy-wrapped entries for each token.
   * Each entry is a {@link createMethodProxy} result.
   */
  services: Record<string, Record<string, Function>>;

  /**
   * Shared Map tracking all pending RPC calls by invokeId.
   * Exposed for advanced use cases (e.g., custom cleanup).
   */
  pendingCalls: Map<string, PendingCall>;

  /**
   * EventBusProxy instance for Worker-side event subscription handling.
   * Handles subscribe/unsubscribe messaging and dispatched forwarded events.
   */
  eventBusProxy: EventBusProxy;

  /**
   * Release all resources: reject all pending calls and clear the
   * onMessage handler. Must be called when the Worker terminates or
   * the plugin is deactivated.
   */
  dispose: () => void;
}

/**
 * Create the full services proxy object for a Worker-side PluginContext.
 *
 * Builds a `services` object with Proxy-wrapped entries for each token string,
 * registers an onMessage handler that dispatches incoming `result`/`error`
 * messages to the matching pending calls, and returns a `dispose` function
 * for cleanup on Worker termination.
 *
 * The services object is frozen with `Object.freeze()` to prevent tampering,
 * following the context-builder.ts pattern (PATTERNS.md line 169).
 *
 * @param transport - Worker transport for cross-thread messaging
 * @param serviceTokens - Array of service token strings to create proxies for
 * @returns {@link ServicesProxyResult} with services, pendingCalls, and dispose
 */
export function createServicesProxy(
  transport: IWorkerTransport,
  serviceTokens: string[],
): ServicesProxyResult {
  const pendingCalls = new Map<string, PendingCall>();
  const eventBusProxy = new EventBusProxy(transport);

  // Register the onMessage handler to dispatch responses
  transport.onMessage((msg: unknown) => {
    const typed = msg as { type?: string; invokeId?: string };

    // Handle forwarded events from EventForwarder
    if (typed.type === 'event') {
      const eventMsg = msg as { subId: string; event: any };
      eventBusProxy.handleEvent(eventMsg.subId, eventMsg.event);
      return;
    }

    const invokeId = typed?.invokeId;
    if (!invokeId) return;

    const pending = pendingCalls.get(invokeId);
    if (!pending) return;
    pendingCalls.delete(invokeId);

    if (typed.type === 'error') {
      const err = new Error(
        (msg as { message?: string }).message ?? 'RPC error',
      );
      err.name = (msg as { code?: string }).code ?? 'RpcError';
      err.stack = (msg as { stack?: string }).stack;
      pending.reject(err);
    } else if (typed.type === 'result') {
      pending.resolve((msg as { value?: unknown }).value);
    }
  });

  // Build services object with Proxy for each token
  const services: Record<string, Record<string, Function>> = {};
  for (const token of serviceTokens) {
    services[token] = createMethodProxy(transport, token, pendingCalls);
  }

  // Freeze the services object to prevent tampering (context-builder.ts pattern)
  Object.freeze(services);

  /**
   * Dispose the proxy: reject all pending calls, dispose EventBusProxy,
   * and clear the onMessage handler. Should be called when the Worker
   * terminates or the plugin is deactivated.
   */
  function dispose(): void {
    // Dispose EventBusProxy subscriptions
    eventBusProxy.disposeAll();

    // Reject all pending calls with transport disposed error
    for (const [, pending] of pendingCalls) {
      pending.reject(
        new WorkerTransportError('Transport disposed'),
      );
    }
    pendingCalls.clear();

    // Clear the onMessage handler by registering a no-op
    transport.onMessage(() => {});
  }

  return { services, pendingCalls, eventBusProxy, dispose };
}
